app/main/models.py
from .. import db


class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    password_hash = db.Column(db.String(120), nullable=True)

    def __repr__(self):
        return '<User %r>' % self.username

app/ml_models/models.py
from app import db
from datetime import datetime


class MLModel(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    model_name = db.Column(db.String(120), unique=True, nullable=False)
    description = db.Column(db.Text, nullable=True)
    pickle_filename = db.Column(db.String(256), unique=True, nullable=False)
    runs = db.relationship('MLModelRun', backref='ml_model', lazy=True)

    def __repr__(self):
        return f'<MLModel {self.model_name}>'


class MLModelRun(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    created_at = db.Column(db.DateTime, default=datetime.now)
    description = db.Column(db.Text, nullable=True)
    csv_filename = db.Column(db.String(256), unique=True, nullable=False)
    ml_model_id = db.Column(db.Integer, db.ForeignKey('ml_model.id'))

    def __repr__(self):
        return f'<MLModelRun of {self.ml_model.model_name} ({self.created_at})>'

app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, ValidationError, PasswordField
from wtforms.validators import DataRequired, Email, EqualTo

from app.models import User


class CreateUser(FlaskForm):
    name = StringField('name', validators=[DataRequired()])
    email = StringField('email', validators=[DataRequired(), Email()])
    password1 = PasswordField('password', validators=[DataRequired(), EqualTo('password2', 'Passwords must match')])
    password2 = PasswordField('repeat password', validators=[DataRequired()])
    submit = SubmitField('Submit')

    def validate_name(self, field):
        if User.query.filter_by(username=field.data).first():
            raise ValidationError('Field name should be unique')

    def validate_email(self, field):
        if User.query.filter_by(email=field.data).first():
            raise ValidationError('Field email should be unique')

app/ml_models/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, FileField, SubmitField
from wtforms.validators import DataRequired


class CreateMLModelForm(FlaskForm):
    model_name = StringField('name', validators=[DataRequired()])
    description = TextAreaField('description')
    pickled_model = FileField(validators=[DataRequired()])
    submit = SubmitField('Submit')


class UploadCSVForm(FlaskForm):
    csv_file = FileField(validators=[DataRequired()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_login import LoginManager
from flask_mail import Mail
from flask_migrate import Migrate
from flask_moment import Moment
from flask_sqlalchemy import SQLAlchemy
from flask_debugtoolbar import DebugToolbarExtension

from app.config import Config

# modules initialization
bootstrap = Bootstrap()
moment = Moment()
db = SQLAlchemy()
mail = Mail()
migrate = Migrate()
login_manager = LoginManager()
login_manager.login_view = "auth.login"
toolbar = DebugToolbarExtension()


def create_app(config=None):
    app = Flask(__name__)
    app.config.from_object(Config)
    if config is not None:
        app.config.update(config)

    bootstrap.init_app(app)
    moment.init_app(app)
    db.init_app(app)
    mail.init_app(app)
    migrate.init_app(app, db=db)
    login_manager.init_app(app)
    toolbar.init_app(app)

    from app.main import bp as main_bp
    from app.auth import bp as auth_bp
    from app.ml_models import bp as ml_models_bp
    app.register_blueprint(main_bp)
    app.register_blueprint(ml_models_bp)
    app.register_blueprint(auth_bp, url_prefix='/auth')

    # add error handlers
    # error handler can't be part of blueprint (https://github.com/pallets/flask/issues/1935)
    with app.app_context():
        from app import errors

    # generate context
    from app.auth.models import User
    from app.ml_models.models import MLModel, MLModelRun
    from app.utils import send_email

    @app.shell_context_processor
    def shell_context():
        return dict(User=User, db=db, mail=mail, send_email=send_email,
                    MLModel=MLModel, MLModelRun=MLModelRun)

    return app

app/main/views.py
from flask import render_template
from flask_login import login_required

from app.auth.models import User
from . import bp


@bp.route('/')
@login_required
def index():
    users = User.query.all()
    return render_template('index.html', users=users)

app/ml_models/__init__.py
from flask import Blueprint

bp = Blueprint('ml_models', __name__)

from . import views

app/ml_models/views.py
import os
from datetime import datetime

from flask import render_template, url_for, current_app, send_from_directory, session, request
from flask_login import login_required
from werkzeug.utils import secure_filename, redirect

from . import bp
from .forms import CreateMLModelForm, UploadCSVForm
from .models import MLModel, MLModelRun
from .. import db


@bp.route('/models/')
@login_required
def models_list():
    page = int(request.values.get('page', 1))
    models_pagination = MLModel.query.paginate(page=page, per_page=current_app.config['PER_PAGE'])
    return render_template('ml_models/models_list.html', models_pagination=models_pagination)


@bp.route('/models/create/', methods=['GET', 'POST'])
@login_required
def model_create():
    form = CreateMLModelForm()
    if form.validate_on_submit():
        f = form.pickled_model.data
        filename = secure_filename(f'{datetime.now().isoformat()}_{f.filename}')
        f.save(os.path.join(
            current_app.config['ML_MODELS_DIR'], filename
        ))
        new_model = MLModel(
            model_name=form.data['model_name'],
            description=form.data.get('description'),
            pickle_filename=filename,
        )
        db.session.add(new_model)
        db.session.commit()
        return redirect(url_for('.models_list'))

    return render_template('ml_models/model_create.html', form=form)


@bp.route('/models/<int:model_id>/')
@login_required
def model_details(model_id):
    page = int(request.values.get('page', 1))
    ml_model = MLModel.query.get_or_404(model_id)
    model_runs_pagnation = MLModelRun.query.filter_by(
        ml_model_id=model_id
    ).order_by(
        MLModelRun.created_at.desc()
    ).paginate(
        page=page, per_page=current_app.config['PER_PAGE']
    )
    return render_template('ml_models/model_details.html', model=ml_model, model_runs_pagnation=model_runs_pagnation)


@bp.route('/models/<int:model_id>/download/')
@login_required
def model_download(model_id):
    ml_model = MLModel.query.get(model_id)
    return send_from_directory(current_app.config['ML_MODELS_DIR'], ml_model.pickle_filename)


@bp.route('/csv/display/', methods=['GET', 'POST'])
@login_required
def csv_display():
    """GET: renders form for uploading CSV and displays recently uploaded file
    POST: submits new CSV file and saves it on server, file path is stored in session"""
    form = UploadCSVForm()
    if form.validate_on_submit():
        f = form.csv_file.data
        filename = secure_filename(f'{datetime.now().isoformat()}_{f.filename}')
        f.save(os.path.join(
            current_app.config['CSV_DIR'], filename
        ))
        session['uploaded_csv'] = filename
        return redirect(url_for('.csv_display'))
    recent_csv_file = session.get('uploaded_csv')
    return render_template('ml_models/csv_display.html', form=form, recent_csv_file=recent_csv_file)

app/views.py
from flask import render_template, flash, redirect, url_for
from werkzeug.security import generate_password_hash

from app import db, app
from app.forms import CreateUser
from app.models import User
from app.utils import send_email


@app.route('/')
def index():
    users = User.query.all()
    return render_template('index.html', users=users)


@app.route('/admin/', methods=['GET', 'POST'])
def admin():
    form = CreateUser()
    if form.validate_on_submit():
        flash(f"You've just created {form.data['name']}")
        new_user = User(
            username=form.data['name'],
            email=form.data['email'],
            password_hash=generate_password_hash(form.data['password1']),
        )
        db.session.add(new_user)
        db.session.commit()
        send_email(to=new_user.email, subject='Account created', template_name='email/new_user',
                   username=new_user.username)
        return redirect(url_for('index'))
    return render_template('admin.html', form=form)

app/templates/admin.html
{% extends "base.html" %}

{% block container %}
    <h1>Add new user</h1>
    <div class="col-md-4">
      <form method="POST">
        {{ wtf.quick_form(form) }}
      </form>
      <hr/>
    </div>
{% endblock container %}

app/templates/base.html
{% extends "bootstrap/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block head %}
{{ super() }}
<link rel="shortcut icon" type="image/png" href="{{ url_for('static', filename='img/flask-icon.png') }}"/>
{% endblock %}

{% block navbar %}
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
              data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">ML Runner</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class=""><a href="{{ url_for('main.index') }}">Strona główna</a></li>
        <li class=""><a href="{{ url_for('ml_models.models_list') }}">ML Models</a></li>
        <li class=""><a href="{{ url_for('ml_models.csv_display') }}">CSV test</a></li>
        {% if current_user.is_admin  %}
          <li class=""><a href="{{ url_for('auth.admin') }}">Admin</a></li>
        {% endif %}
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
             aria-expanded="false">
            {% if current_user.is_authenticated %}
              {{ current_user.username }}
              {% if current_user.is_admin %}
                (Admin)
              {% endif %}
            {% endif %}
            <span class="caret"></span></a>
          {% if current_user.is_authenticated %}
            <ul class="dropdown-menu">
              <li><a href="{{ url_for('auth.logout') }}">Log out</a></li>
            </ul>
          {% endif %}
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
{% endblock navbar %}

{% block content %}
  <div class="container">
    {% block breadcrumbs %}
    {% endblock %}

    {% for message in get_flashed_messages() %}
      <div class="alert alert-info alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                aria-hidden="true">&times;</span></button>
        {{ message }}
      </div>
    {% endfor %}
    {% block container %}
    {% endblock container %}
  </div>
{% endblock content %}

{% block scripts %}
  {{ super() }}
  {{ moment.include_moment() }}
{% endblock scripts %}

app/templates/index.html
{% extends "base.html" %}

{% block container %}
      <h1>Users in db</h1>
      <ul>
      {% for user in users %}
          <li>{{ user.username }} {% if user.is_admin %}[Admin]{% endif %} ({{ user.email }})</li>
      {% endfor %}
      </ul>
    </div>
{% endblock container %}

app/templates/ml_models/csv_display.html
{% extends "base.html" %}

{% block container %}
  <h1>Add new model</h1>
  <div class="col-md-4">
    <form method="POST" enctype="multipart/form-data">
      {{ wtf.quick_form(form) }}
    </form>
    <hr/>
    {% if recent_csv_file %}
      <h2>Recently uploaded file:</h2>
      <div>{{ recent_csv_file }}</div>
    {% endif %}
  </div>
{% endblock container %}

app/templates/ml_models/model_create.html
{% extends "base.html" %}

{% block container %}
    <h1>Add new model</h1>
    <div class="col-md-4">
      <form method="POST" enctype="multipart/form-data">
        {{ wtf.quick_form(form) }}
      </form>
      <hr/>
    </div>
{% endblock container %}

app/templates/ml_models/model_details.html
{% extends "base.html" %}

{% block breadcrumbs %}
  <ol class="breadcrumb">
    <li><a href="{{ url_for('ml_models.models_list') }}">ML Models</a></li>
    <li class="active">ML Model details</li>
  </ol>
{% endblock %}
{% block container %}
  <h1>ML Model details</h1>
  <ul class="list-group">
    <li class="list-group-item"><strong>id:</strong> {{ model.id }}</li>
    <li class="list-group-item"><strong>Model name:</strong> {{ model.model_name }}</li>
    <li class="list-group-item"><strong>Description:</strong> {{ model.description }}</li>
    <li class="list-group-item">
      <a href="{{ url_for('ml_models.model_download', model_id=model.id) }}" target="_blank">
        download {{ model.pickle_filename }}
      </a>
    </li>
  </ul>

  <hr/>
  <h2>Related runs</h2>
  <table class="table">
    <thead>
      <tr>
        <th>Date of creation</th>
        <th>Description</th>
        <th>Input file</th>
      </tr>
    </thead>
    <tbody>
      {% for run in model_runs_pagnation.items %}
        <tr>
          <td>{{ run.created_at }}</td>
          <td>{{ run.description|truncate(32) }}</td>
          <td>{{ run.csv_filename }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

  <div>
    Displaying {{ model_runs_pagnation.per_page }} of {{ model_runs_pagnation.total }}
  </div>
  <nav aria-label="Page navigation">
    <ul class="pagination">
      {% for page in model_runs_pagnation.iter_pages(left_edge=2, left_current=2, right_current=2, right_edge=2) %}
        {% if not page %}
          <li><a>...</a></li>
        {% elif page == model_runs_pagnation.page %}
          <li><a><strong>{{ page }}</strong></a></li>
        {% else %}
          <li><a href="{{ url_for('ml_models.model_details', model_id=model.id, page=page) }}">{{ page }}</a></li>
        {% endif %}
      {% endfor %}
    </ul>
  </nav>
{% endblock container %}

app/templates/ml_models/models_list.html
{% extends "base.html" %}

{% block breadcrumbs %}
  <ol class="breadcrumb">
    <li class="active">ML Models</li>
  </ol>
{% endblock %}

{% block container %}
    <h1>ML Models</h1>
    <div>
      Displaying {{ models_pagination.per_page }} of {{ models_pagination.total }}
    </div>
    <nav aria-label="Page navigation">
      <ul class="pagination">
        {% for page in models_pagination.iter_pages(left_edge=2, left_current=2, right_current=2, right_edge=2) %}
          {% if not page %}
            <li><a>...</a></li>
          {% elif page == models_pagination.page %}
            <li><a><strong>{{ page }}</strong></a></li>
          {% else %}
            <li><a href="{{ url_for('ml_models.models_list', page=page) }}">{{ page }}</a></li>
          {% endif %}
        {% endfor %}
      </ul>
    </nav>
    <ul>
    {% for model in models_pagination.items %}
      <li>
        {{ model.model_name }}
        <a href="{{ url_for('ml_models.model_details', model_id=model.id) }}">
          [details]
        </a>
        <a href="{{ url_for('ml_models.model_download', model_id=model.id) }}"  target="_blank">
          [download]
        </a>
      </li>
    {% endfor %}
  </ul>
  <a class="btn btn-lg btn-success" href="{{ url_for('ml_models.model_create') }}">
    <span class="glyphicon glyphicon-plus"></span>
    Add new model
  </a>
{% endblock container %}